Implement wlr_xwayland_server from QWXWaylandServer
vioken/qwlroots pull request #137
Opened 2023-06-28 03:49 UTC by justforlxz

2023-06-28 10:12 UTC, zccrs requested changes

2023-06-28 10:12 UTC, zccrs commented on src/types/qwxwaylandserver.h
> +QW_END_NAMESPACE
Add an empty line

2023-06-28 10:12 UTC, zccrs commented on src/types/qwxwaylandserver.cpp
> +    void on_start(void *);
Where is to connect this signal?

2023-06-28 11:52 UTC, wineee commented on src/types/qwxwaylandserver.h
>  public:
```
~QWXWaylandServer()=default;
```
Explicitly declare the destructor is `public`

2023-06-29 01:32 UTC, zccrs approved these changes

2023-06-29 02:17 UTC, merged