refactor: make header only
vioken/qwlroots pull request #250
Opened 2024-07-01 10:27 UTC by wineee

2024-07-01 10:38 UTC, zccrs requested changes

2024-07-01 10:38 UTC, zccrs commented on src/types/qwdrm.h
> +    QW_FUNC_MEMBER(drm, create)
should static?

2024-07-01 10:38 UTC, zccrs commented on src/types/qwdrm.h
> +    QW_FUNC_MEMBER(drm_buffer, try_from_resource)
static?

2024-07-02 02:04 UTC, wineee commented on src/types/qwdrm.h
> +    QW_FUNC_MEMBER(drm, create)
Yes

2024-07-02 02:30 UTC, zccrs requested changes

2024-07-02 02:30 UTC, zccrs commented on src/types/qwdamagering.h
> +    QW_FUNC_MEMBER(damage_ring, init)
auto init in constructor

2024-07-02 02:30 UTC, zccrs commented on src/types/qwdamagering.h
> +    QW_FUNC_MEMBER(damage_ring, finish)
auto finish in destructor

2024-07-02 02:31 UTC, zccrs approved these changes

2024-07-02 02:31 UTC, merged