clear up and init qwoutputlayer qwtearingcontrolv1
vioken/qwlroots pull request #258
Opened 2024-07-04 09:50 UTC by wineee

2024-07-04 10:50 UTC, wineee commented on src/types/qwswitch.h
>  #include <qwinputdevice.h>
忘了删除

2024-07-05 02:03 UTC, zccrs requested changes

2024-07-05 02:03 UTC, zccrs commented on src/types/qwoutputlayer.h
> +// Copyright (C) 2024 rewine <luhongxu@deepin.org>.
UnionTech Software Technology Co., Ltd.

2024-07-05 02:39 UTC, zccrs requested changes

2024-07-05 02:39 UTC, zccrs commented on src/types/qwoutputlayer.h
> +    QW_SIGNAL(feedback, wlr_output_layer_feedback_event*)
add a new line between of Q_OBJECT and QW_SIGNAL

2024-07-05 02:39 UTC, zccrs commented on src/types/qwgammacontorlv1.h
> +    QW_FUNC_MEMBER(gamma_control_manager_v1, get_control)
add a new line between of QW_FUNC_STATIC and QW_FUNC_MEMBER code blocks.

2024-07-05 02:56 UTC, merged