feat: add flake support
vioken/qwlroots pull request #26
Opened 2023-03-14 03:27 UTC by wineee

2023-03-14 09:11 UTC, zccrs requested changes

2023-03-14 09:11 UTC, zccrs commented on flake.nix
> +  description = "A basic flake to help develop wlroots";
应该是 qwlroots ？

2023-03-14 09:11 UTC, zccrs commented on flake.nix
> +          qwlroots = pkgs.libsForQt5.callPackage ./nix {
能同时打出两个包吗，一个基于Qt5，一个基于Qt6。如果不行就默认为Qt6，今后最低要求可能就是Qt6了。

2023-03-14 09:11 UTC, zccrs commented on flake.nix
> +              # (weston.override { buildDemo = true; })
这个注释？

2023-03-14 09:11 UTC, zccrs commented on flake.nix
> +              export QT_LOGGING_RULES="*.debug=true;qt.*.debug=false"
为了调试需要？

2023-03-14 09:11 UTC, zccrs commented on flake.nix
> +              export QT_LOGGING_RULES="*.debug=true;qt.*.debug=false"
是不是wlroots的log也可以打开

2023-03-14 09:12 UTC, wineee commented on flake.nix
> +          qwlroots = pkgs.libsForQt5.callPackage ./nix {
可以

2023-03-14 09:16 UTC, wineee commented on flake.nix
> +              # (weston.override { buildDemo = true; })
weston 项目自带的一些简易客户端例子 nixpkgs 默认不编译，这个会本地编译 weston，所以注释了，我本地是取消注释的

2023-03-14 09:17 UTC, wineee commented on flake.nix
> +              export QT_LOGGING_RULES="*.debug=true;qt.*.debug=false"
对应环境变量是什么

2023-03-14 09:22 UTC, wineee commented on flake.nix
> +          qwlroots = pkgs.libsForQt5.callPackage ./nix {
需要 wlroots 17 吗，后面也可以加上和 dde-nixos 一样的 ci

2023-03-14 09:43 UTC, zccrs commented on flake.nix
> +              export QT_LOGGING_RULES="*.debug=true;qt.*.debug=false"
> 对应环境变量是什么

算了，它好像没提供环境变量

2023-03-15 03:26 UTC, wineee commented
https://github.com/vioken/qwlroots/pull/29

2023-03-15 03:26 UTC, closed without merging