Implement QWSeat for wlr_seat
vioken/qwlroots pull request #27
Opened 2023-03-14 04:15 UTC by wineee

2023-03-14 09:31 UTC, zccrs requested changes

2023-03-14 09:31 UTC, zccrs commented on src/types/qwseat.h
> +// Copyright (C) 2022 JiDe Zhang <zccrs@live.com>.
不应该是我的信息，应该是你的

2023-03-14 09:31 UTC, zccrs commented on src/types/qwseat.h
> +typedef int wlr_axis_orientation_t;
没有编译报错吗？

2023-03-14 09:31 UTC, zccrs commented on src/types/qwseat.h
> +    void setKeyboard(wlr_keyboard *keyboard);
用QWKeyboard？

2023-03-14 09:31 UTC, zccrs commented on src/types/qwseat.h
> +    wlr_keyboard *getKeyboard() const;
同上

2023-03-14 09:31 UTC, zccrs commented on src/types/qwseat.h
> +    void pointer_grab_begin();
信号的命名要遵从Qt的风格，改为驼峰

2023-03-14 09:31 UTC, zccrs commented on src/types/qwseat.cpp
> +// Copyright (C) 2022 JiDe Zhang <zccrs@live.com>.
同头文件

2023-03-14 09:31 UTC, zccrs commented on src/types/qwseat.h
> +private:
将析构函数定义为 private，wlr_seat 会跟随 wl_display 自动销毁。QWSeat 只需要跟随 wlr_seat 销毁就行。

2023-03-14 09:31 UTC, zccrs commented on src/types/qwseat.h
> +    void destroy();
不需要在c++里提供销毁函数。

2023-03-14 09:33 UTC, wineee commented on src/types/qwseat.h
> +typedef int wlr_axis_orientation_t;
wlr_axis_orientation_t 不是 wlr_axis_orientation，这个其实还是 int, 只是换个近似的名字

2023-03-14 09:47 UTC, zccrs commented on src/types/qwseat.h
> +typedef int wlr_axis_orientation_t;
可以

2023-03-15 05:35 UTC, wineee commented on src/types/qwseat.h
> +    void setKeyboard(wlr_keyboard *keyboard);
QWKeyboard 没有写完，下个 pr 更新

2023-03-15 06:19 UTC, wineee commented on src/types/qwseat.cpp
> +        if (isHandleOwner)
禁止 QWSeat 析构这里还会运行吗？ 或者是这里有意义吗？

2023-03-15 06:22 UTC, zccrs commented on src/types/qwseat.cpp
> +        if (isHandleOwner)
有，因为这个禁止毕竟不是绝对的，只能算是一个标识，实际上使用者还是有可能通过调用 QObject::deleteLater() 销毁它，所以 qwlroots 的代码中还是需要处理析构。

2023-03-15 11:37 UTC, zccrs commented on src/types/qwseat.cpp
> +        if (isHandleOwner)
这是两个概念，这里的 owner 不用管这个对象会不会跟随 wl_display 被销毁，它只是用来记录这个对象是不是被主动 create 出来的，如果是的，我们是期望把这个 wlr_xxxx 对象和它对应  QWXXXX 对象的生命周期严格绑定到一起，即双方的任何一方被销毁，都应该销毁另外一方。

至于说使用者在知道（也可能不知道） QWSeat 会跟随 wl_display 销毁的情况下还要选择自己销毁它，这个行为与在使用 wlroots 时调用 wlr_seat_destroy 没有区别，调用方自己负责就行了。

在 qwlroots 中把这类会自动销毁的对象的析构标记为 private，仅仅是用于方便使用者从接口上就能知道这个对象存在自动销毁的行为，除此之外没有其他作用，如果我们不用这个行为来标识它，也可以用在“添加文档说明”这种方式，这仅仅是一种标记手段。

2023-03-15 11:54 UTC, zccrs requested changes

2023-03-15 11:54 UTC, zccrs commented on src/types/qwseat.h
> +    void setSelection();
改为 selectionChanged，setXXXX 这种命名风格，在Qt里往往是一个普通函数，不可能出现在信号里，Qt用于统治一个东西变化，往往是用 XXXXChanged 这种风格。

2023-03-15 11:54 UTC, zccrs commented on src/types/qwseat.h
> +    void setPrimarySelection();
同上

2023-03-16 03:34 UTC, zccrs approved these changes

2023-03-16 03:35 UTC, merged