[WIP] Implement QWInputDevice/QWKeyBoard for wlr_input_device/wlr_key_board
vioken/qwlroots pull request #44
Opened 2023-03-23 09:28 UTC by wineee

2023-03-24 03:17 UTC, wineee commented on examples/tinywl/main.cpp
> -void TinywlServer::onKeyboardDestroy(void *, wlr_keyboard *keyboard)
有两个问题
1. destroy 这个信号是 QWInputDevice 转发的，不能直接传 QWKeyboard

2. 这里希望在 QWKeyboard 析构时 sc.disconnect，
应该在析构函数里使用 d_func()->deleteLater() 吗

2023-03-25 11:27 UTC, wineee commented on src/CMakeLists.txt
> +    PRIVATE_HEADER
如果 PRIVATE_HEADER 不安装会有个警告：
```
Target qwlroots has PRIVATE_HEADER files but no PRIVATE_HEADER DESTINATION.
```

2023-03-25 12:02 UTC, wineee commented on src/types/qwinputdevice.cpp
> +    //if (isHandleOwner)
这里应该 delete 对应 q_func()->handle() 的吗

2023-03-27 10:10 UTC, zccrs requested changes

2023-03-28 03:00 UTC, wineee commented on src/CMakeLists.txt
> +    PRIVATE_HEADER
PUBLIC_HEADER/PRIVATE_HEADER 应该是 cmake 3.15 的新特性，加入 add_library 也可以
```
add_library(${TARGET}
    SHARED
    ${SOURCES}
    ${HEADERS}
    ${PRIVATE_HEADERS}
)
```
另外 qt creator 9.2 如果只设置 PUBLIC_HEADER 不设置 add_library，project 视图会不显示头文件

2023-03-28 03:04 UTC, wineee commented on examples/tinywl/main.cpp
> +    if (device->handle()->type == WLR_INPUT_DEVICE_KEYBOARD) {
c++17 和 qt5 的相性似乎不好

2023-03-28 06:22 UTC, zccrs requested changes

2023-03-28 06:22 UTC, zccrs commented on src/types/qwkeyboard.h
> +#include <QObject>
这个放后放，放到本项目的头文件的下面

2023-03-28 06:22 UTC, zccrs commented on src/types/qwkeyboard.h
> +    uint32_t getModifiers();
可以加一个 const 修饰函数自身？

2023-03-28 06:22 UTC, zccrs commented on src/types/qwkeyboard.h
> +    void repeat_info();
这里不应该是下划线风格

2023-03-28 06:22 UTC, zccrs commented on src/types/qwkeyboard.h
> +    void repeat_info();
这里是不是应该是 repeatInfoChanged?

2023-03-28 06:22 UTC, zccrs commented on src/types/qwkeyboard.h
> +    void keymap();
应该是 keymapChanged 吗？

2023-03-28 06:22 UTC, zccrs commented on src/types/qwkeyboard.h
> +    void modifiers(QWKeyboard *keyboard);
同下。另外这里的 keyboard 是 this 吗？如果是，不用给出这个参数

2023-03-28 06:22 UTC, zccrs commented on src/types/qwkeyboard.h
> +    void key(wlr_keyboard_key_event *event, QWKeyboard *keyboard);
这里的 keyboard 应该没必要给出。

2023-03-28 06:23 UTC, zccrs commented on examples/tinywl/main.cpp
> +    if (device->handle()->type == WLR_INPUT_DEVICE_KEYBOARD) {
会有什么问题/

2023-03-28 06:23 UTC, zccrs requested changes

2023-03-28 06:23 UTC, zccrs commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
为什么需要开启 17 ？这里能设置一个最小要求的版本吗，或者是根据Qt的版本给出一个版本？

2023-03-28 06:32 UTC, wineee commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
改回 11 了

2023-03-28 06:46 UTC, wineee commented on src/types/qwkeyboard.h
> +    void repeat_info();
应该是，在 wlr_keyboard_set_repeat_info 会触发这个信号

2023-03-28 06:50 UTC, wineee commented on src/types/qwkeyboard.h
> +    void keymap();
应该是

2023-03-28 06:52 UTC, wineee commented on src/types/qwkeyboard.h
> +    void modifiers(QWKeyboard *keyboard);
调用时使用 `QObject::sender()` 更好吗？

2023-03-28 07:45 UTC, wineee commented on src/types/qwkeyboard.h
> +    void modifiers(QWKeyboard *keyboard);
这两个改了

2023-03-28 07:47 UTC, zccrs approved these changes

2023-03-28 07:53 UTC, merged