Implement QWKeyboardInterface form wlr_keyboard
vioken/qwlroots pull request #52
Opened 2023-04-20 07:52 UTC by wineee

2023-04-20 08:28 UTC, wineee commented on src/interfaces/qwkeyboardinterface.h
> +    virtual void ledUpdate(uint32_t leds) const;
ledUpdate 是唯一需要实现的函数，是不是改成纯虚函数更好？

2023-04-20 08:51 UTC, wineee commented
obs 工作流 token 过期了

2023-04-23 06:39 UTC, zccrs requested changes

2023-04-23 06:39 UTC, zccrs commented on src/interfaces/qwkeyboardinterface.cpp
> +}
标记一下// end namespace impl

2023-04-23 06:39 UTC, zccrs commented on src/interfaces/qwkeyboardinterface.h
> +        init("wlr_keyboard_empty_impl", getFuncMagicKey<T>(&T::ledUpdate));
这里的名字会有什么用途，是不是让派生类自己指定名字比较好

2023-04-23 06:39 UTC, zccrs commented on src/interfaces/qwkeyboardinterface.cpp
> +    m_handle = new _wlr_keyboard(this);
改为C的方式，用 calloc

2023-04-23 06:39 UTC, zccrs commented on src/interfaces/qwkeyboardinterface.cpp
> +    delete handle();
改成C的方式，用free(handle())

2023-04-23 07:00 UTC, wineee commented on src/interfaces/qwkeyboardinterface.h
> +        init("wlr_keyboard_empty_impl", getFuncMagicKey<T>(&T::ledUpdate));
[wlr_keyboard_impl](https://wayland.emersion.fr/wlroots/wlr/interfaces/wlr_keyboard.h.html#struct-wlr_keyboard_impl) 的成员变量，wlr_keyboard_init 时会拷贝一份，

派生类应该重载 init 函数，指定自己的名字，这个类是空实现，按理说应该写成纯虚类，这个 init 不应该被调用

2023-04-23 07:32 UTC, wineee commented on src/interfaces/qwkeyboardinterface.cpp
> +    m_handle = new _wlr_keyboard(this);
_wlr_keyboard 的构造函数有没有必要禁用

2023-04-23 08:35 UTC, zccrs requested changes

2023-04-23 08:35 UTC, zccrs commented on src/interfaces/qwkeyboardinterface.h
> +        init("wlr_keyboard_empty_impl", getFuncMagicKey<T>(&T::ledUpdate));
那就加一个返回 name 的纯虚函数，在这个init里调用获取name.

2023-04-23 08:35 UTC, zccrs commented on src/interfaces/qwkeyboardinterface.h
> +    virtual void ledUpdate(uint32_t leds) const;
要考虑这个函数是不是可选的，如果不是，应该为纯虚

2023-04-23 08:35 UTC, zccrs commented on src/interfaces/qwkeyboardinterface.cpp
> +    m_handle = new _wlr_keyboard(this);
> _wlr_keyboard 的构造函数有没有必要禁用

不用，它只在 cpp 里，不会被误用

2023-04-24 03:49 UTC, wineee commented on src/interfaces/qwkeyboardinterface.h
> +        init("wlr_keyboard_empty_impl", getFuncMagicKey<T>(&T::ledUpdate));
如果需要返回 name 的函数，返回的都是 wlr_keyboard_impl 不需要重载吧，不应该是纯虚函数

另外init是需要给 name 赋值，不是获取name

2023-04-24 03:53 UTC, wineee commented on src/interfaces/qwkeyboardinterface.h
> +    virtual void ledUpdate(uint32_t leds) const;
仅凭名字推测 ledUpdate 应该是可选的，暂时先保持现状，以后实现更多功能时再看看要不要调整

2023-04-24 06:30 UTC, zccrs commented on src/interfaces/qwkeyboardinterface.h
> +        init("wlr_keyboard_empty_impl", getFuncMagicKey<T>(&T::ledUpdate));
返回 name 的纯虚函数让为了让派生类一定要提供name，在派生类里重载 init() 后再修改 name 的方式也可以，不过这里直接给一个 nullptr 的char*就行了，不用默认传一个 "wlr_keyboard_empty_impl"，但是这样就做不到强制要求派生类一定要提供一个name，从实现角度来说可以看看如果name是nullptr会怎么样，如果不怎么样，那派生类替补提供都无所谓。

2023-04-27 08:57 UTC, wineee commented on src/interfaces/qwkeyboardinterface.h
> +        init("wlr_keyboard_empty_impl", getFuncMagicKey<T>(&T::ledUpdate));
已修改

2023-04-27 09:18 UTC, zccrs approved these changes

2023-04-27 09:18 UTC, merged