Implement QWEgl from wlr_egl
vioken/qwlroots pull request #75
Opened 2023-06-06 08:51 UTC by justforlxz

2023-06-07 02:02 UTC, wineee commented
对于没有提供信号，且在封装的 class 中无需任何成员变量时，可直接将 wlroots 的结构体指针强转为对应的 class 指针使用。可参考 [QWTexture 的实现](https://github.com/vioken/qwlroots/blob/master/src/render/qwtexture.cpp#L28)

这个应该符合

2023-06-07 06:25 UTC, justforlxz commented
> 对于没有提供信号，且在封装的 class 中无需任何成员变量时，可直接将 wlroots 的结构体指针强转为对应的 class 指针使用。可参考 [QWTexture 的实现](https://github.com/vioken/qwlroots/blob/master/src/render/qwtexture.cpp#L28)
> 
> 这个应该符合

done

2023-06-14 08:42 UTC, zccrs requested changes

2023-06-15 03:20 UTC, zccrs approved these changes

2023-06-15 03:20 UTC, merged