Implement QWSwapchain from wlr_swapchain
vioken/qwlroots pull request #76
Opened 2023-06-07 01:43 UTC by justforlxz

2023-06-07 03:28 UTC, justforlxz commented
wait for https://github.com/vioken/qwlroots/pull/77

2023-06-14 08:46 UTC, zccrs requested changes

2023-06-14 08:46 UTC, zccrs commented on src/render/qwswapchain.cpp
> +#include "qwswapchain.h"
copyright

2023-06-14 08:46 UTC, zccrs commented on src/render/qwswapchain.cpp
> +QWSwapchain *QWSwapchain::create(QWAllocator alloc, QSize size, const wlr_drm_format *format)
`QWAllocator *`?

2023-06-15 03:05 UTC, zccrs approved these changes

2023-06-15 03:05 UTC, merged