Implement implement qwxwayland signals from wlr_xwayland
vioken/qwlroots pull request #88
Opened 2023-06-15 08:48 UTC by justforlxz

2023-06-15 09:20 UTC, zccrs requested changes

2023-06-15 09:20 UTC, zccrs commented on src/types/qwxwayland.cpp
> +    ~QWXWaylandPrivate() {
See https://github.com/vioken/qwlroots/blob/master/src/class_template.txt#L59
Keep template code.

2023-06-15 09:20 UTC, zccrs commented on src/types/qwxwayland.cpp
> +    return new QWXWayland(wlr_xwayland_create(wl_display->handle(), compositor->handle(), lazy), true);
The return value of `wlr_xwayland_create` maybe is nullptr

2023-06-15 09:20 UTC, zccrs commented on src/types/qwxwayland.cpp
> +    : QObject()
Where is parent argument?

2023-06-15 09:20 UTC, zccrs commented on src/types/qwxwayland.h
> +Q_SIGNALS:
The signals's name keep Qt style.

2023-06-15 15:19 UTC, wineee commented on src/types/qwxwayland.cpp
> +        Q_ASSERT(map.contains(m_handle));
应该不是每个信号都要检查这个， destroy有应该就够了

2023-06-16 00:23 UTC, justforlxz commented on src/types/qwxwayland.cpp
> +        Q_ASSERT(map.contains(m_handle));
反正是无参的，直接绑定到public class上面了。

2023-06-16 01:36 UTC, zccrs requested changes

2023-06-16 01:36 UTC, zccrs commented on src/types/qwxwayland.h
> +class QWXWayland : public QObject, public QWObject
`QW_EXPORT`

2023-06-16 02:39 UTC, zccrs approved these changes

2023-06-16 02:39 UTC, merged