Implement QWShm from wlr_shm
vioken/qwlroots pull request #92
Opened 2023-06-16 06:25 UTC by wineee

2023-06-16 06:38 UTC, zccrs requested changes

2023-06-16 06:38 UTC, zccrs commented on src/types/qwshm.h
> +    QWShm() = default;
= delete

2023-06-16 06:40 UTC, wineee commented on src/types/qwshm.h
> +    void destroy();
qwtexture 拷贝的忘了删了

2023-06-19 05:19 UTC, zccrs approved these changes

2023-06-19 05:19 UTC, merged